collections:
  konzerte:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default-container"

picture:
  output: "assets/images/generated"

sass:
  load_paths:
    - _sass
    - vendor/bundle/ruby/3.4.2/gems/bootstrap-5.3.3/assets/stylesheets/

exclude:
  - Makefile

permalink: /:slug/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: Principium Canti
tagline: Das Männervokalensemble aus Lindenholzhausen
description: >
  Principium Canti ein bunt zusammengewürfeltes, 13-köpfiges Männervokalensemble aus dem Sängerdorf Lindenholzhausen.
locale: de_DE
social:
  name: Principium Canti
  links:
    - https://www.facebook.com/Principium-Canti-184616798647339/
    - https://www.instagram.com/principiumcanti/
    - https://www.youtube.com/channel/UC5MElhUXD670ymInkP3Isbw