backend:
  name: git-gateway
  branch: main
  repo: "principiumcanti/website"

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"
public_folder: "assets/images/uploads"
site_url: https://principiumcanti.de
display_url: https://principiumcanti.de
logo_url: https://principiumcanti.de/assets/images/logo/PrincipiumCanti.svg
locale: 'de'

collections:
  - name: "artikel" # Used in routes, e.g., /admin/collections/blog
    label: "Artikel" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string", required: true }
      - {label: "Subtitel", name: "subtitle", widget: "string"}
      - {label: "Pressebericht", name: "pressebericht", widget: "boolean", default: true }
      - {label: "Quellenname", name: "quelle-name", widget: "string"}
      - {label: "Quellenlink", name: "quelle-link", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Artikelbild"
        name: "image"
        widget: "object"
        collapsed: false
        fields:
          - {label: "Bild", name: "url", widget: "image", required: true, allowMultiple: false}
          - {label: "Alternativtext", name: "alt-text", widget: "text", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "konzerte"
    label: "Konzerte"
    folder: "_konzerte"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string", required: true }
      - {label: "Datum", name: "date", widget: "date", required: true }
      - {label: "PLZ", name: "zip", widget: "string", required: false}
      - {label: "Adresse", name: "address", widget: "string", required: false}
      - {label: "Zeit", name: "time", widget: "string", required: false}
      - {label: "Anzeige", name: "show", widget: "boolean", required: true }
  - name: "seiten"
    label: "Seiten"
    files:
      - name: "startseite"
        label: "Startseite"
        file: "_data/frontpage.yml"
        fields:
          - label: "Infobox"
            name: "infobox"
            widget: object
            fields:
              - label: "Herz"
                name: "herz"
                widget: object
                fields:
                  - {label: Titel, name: heading, widget: string}
                  - {label: Text, name: text, widget: text }
              - label: "Note"
                name: "note"
                widget: object
                fields:
                  - { label: Titel, name: heading, widget: string }
                  - { label: Text, name: text, widget: text }
          - label: "Über uns"
            name: "ueber-uns"
            widget: object
            fields:
              - { label: Titel, name: heading, widget: string }
              - { label: Text, name: text, widget: text }
          - label: "Kontakt"
            name: "kontakt"
            widget: object
            fields:
              - { label: Titel, name: heading, widget: string }
              - { label: Text, name: text, widget: text }
      - name: "impressum"
        label: "Impressum"
        file: "impressum.md"
        preview_path: "impressum"
        fields: # The fields for each document, usually in front matter
          - { label: "Titel", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "datenschutzerklaerung"
        label: "Datenschutzerklärung"
        file: "datenschutzerklaerung.md"
        preview_path: "datenschutzerklaerung"
        fields: # The fields for each document, usually in front matter
          - { label: "Titel", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }

